# runtime: python27
# runtime: nodejs14
# api_version: 1
# threadsafe: true
# handlers:
# - url: /
#  static_files: frontend/index.html
#  upload: frontend/index.html
# - url: /
# static_dir: frontend

runtime: nodejs14
handlers:
  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/frontend/\1
    upload: dist/frontend/(.*)(|\.map)
  - url: /.*
    static_files: dist/frontend/index.html
    upload: dist/frontend/.*
